[package]
name = "microkelvin"
version = "0.1.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
canonical = { path = "../canonical/canon", features = ["host"] }
canonical_derive = { path = "../canonical/canon_derive" }
canonical_host = { path = "../canonical/canon_host" }
