[package]
name = "microkelvin"
version = "0.1.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
canonical = { version = "0.3", features = ["host"] }
canonical_derive = "0.3"
canonical_host = "0.3"
